/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prajval_bhoyar;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Deshmukh's
 */
public class Bhoyar_mp extends javax.swing.JFrame {

    /**
     * Creates new form Bhoyar_mp
     */
    public Bhoyar_mp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        MEDIAN = new javax.swing.JButton();
        v = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MIN = new javax.swing.JButton();
        MINA = new javax.swing.JButton();
        MODE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Result:");

        result.setText("0");

        MEDIAN.setText("MEDIAN");
        MEDIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIANActionPerformed(evt);
            }
        });

        jLabel3.setText("Value");

        MIN.setText("MIN");
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });

        MINA.setText("MINA");
        MINA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINAActionPerformed(evt);
            }
        });

        MODE.setText("MODE");
        MODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MEDIAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MINA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MODE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEDIAN)
                    .addComponent(MIN)
                    .addComponent(MINA)
                    .addComponent(MODE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MEDIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIANActionPerformed
        // TODO add your handling code here:
        String s1=v.getText();
        String arr[] = s1.split(",");
        int n=arr.length;
        Double [] arr1=new Double[n];
        for (int i = 0; i < n; i++) {
            arr1[i] = Double.parseDouble(arr[i]);
        }
        Arrays.sort(arr1);
        if (n % 2 != 0)
        {
            double std=arr1[n / 2];
            String s5=String.valueOf(std);
            result.setText(s5);
        }
        double std=(arr1[(n - 1) / 2] + arr1[n / 2]) / 2.0;
        String s5=String.valueOf(std);
        result.setText(s5);
    }//GEN-LAST:event_MEDIANActionPerformed

    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        String s1=v.getText();
        String arr[] = s1.split(",");
        int n=arr.length;
        Double [] arr1=new Double[n];
        int i;
        try{
        for ( i = 0; i < n; i++) 
        {
            arr1[i] = Double.parseDouble(arr[i]);
  
        }
        }catch(NumberFormatException e)
        {
            String s5="Error value";
            result.setText(s5);
        }
        
        double res = arr1[0];
        for (i = 1; i < n; i++){
            res = (int) Math.min(res, arr1[i]);  
            String s5=String.valueOf(res);
            result.setText(s5);
        }
            
    }//GEN-LAST:event_MINActionPerformed

    private void MINAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINAActionPerformed
        // TODO add your handling code here:
        String s1=v.getText();
        String arr[] = s1.split(",");
        int n=arr.length;
        Double [] arr1=new Double[n];
        int i;
         for ( i = 0; i < n; i++) {
           if(arr[i].equals("TRUE")==true){
               arr1[i]=1.0;
           }else{
               if(arr[i].equals("FALSE")==true){
               arr1[i]=0.0;
           }else{
                    arr1[i] = Double.parseDouble(arr[i]);
                   
               }
           }  
         }
        double res = arr1[0];
        for (i = 1; i < n; i++){
            res = (int) Math.min(res, arr1[i]);  
            String s5=String.valueOf(res);
            result.setText(s5);
        }

    }//GEN-LAST:event_MINAActionPerformed

    private void MODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODEActionPerformed
        // TODO add your handling code here:
        String s1=v.getText();
        String arr[] = s1.split(",");
        int n=arr.length;
        Integer [] arr1=new Integer[n];
        for (int i = 0; i < n; i++) {
            arr1[i] = Integer.parseInt(arr[i]);
        }
        int maxValue = 0, maxCount = 0, i, j;

      for (i = 0; i < n; ++i) {
         int count = 0;
         for (j = 0; j < n; ++j) {
            if (arr1[j] == arr1[i])
            ++count;
         }

         if (count > maxCount) {
            maxCount = count;
            maxValue = arr1[i];
         }
        }
        double mode= maxValue;
        String s5=String.valueOf(mode);
        result.setText(s5);
    }//GEN-LAST:event_MODEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bhoyar_mp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bhoyar_mp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bhoyar_mp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bhoyar_mp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bhoyar_mp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MEDIAN;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MINA;
    private javax.swing.JButton MODE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField result;
    private javax.swing.JTextField v;
    // End of variables declaration//GEN-END:variables
}
